[chipflow]
project_name = "sram"

[chipflow.top]
soc = "design.design:MySoC"

[chipflow.steps]
silicon = "chipflow_lib.steps.silicon:SiliconStep"

[chipflow.silicon]
process = "sky130"
package = "openframe"
