[chipflow]
project_name = "upcounter"

[chipflow.top]
soc = "design.design:MySoC"

[chipflow.steps]
silicon = "chipflow_lib.steps.silicon:SiliconStep"

[chipflow.silicon]
process = "ihp_sg13g2"
package = "pga144"
#process = "sky130"
#package = "openframe"

